# This file was automatically generated by bakefile.
#
# Any manual changes will be lost if it is regenerated,
# modify the source .bkl file instead if possible.

# You may define standard make variables such as CFLAGS or
# CXXFLAGS to affect the build. For example, you could use:
#
#      make CXXFLAGS=-g
#
# to build with debug information. The full list of variables
# that can be used by this makefile is:
# AR, CC, CFLAGS, CPPFLAGS, CXX, CXXFLAGS, LD, LDFLAGS, MAKE, RANLIB.

# You may also specify config=Debug|Release
# or their corresponding lower case variants on make command line to select
# the corresponding default flags values.
ifeq ($(config),debug)
override config := Debug
endif
ifeq ($(config),release)
override config := Release
endif
ifeq ($(config),Debug)
override CPPFLAGS += -DDEBUG
override CFLAGS += -g -O0
override CXXFLAGS += -g -O0
override LDFLAGS += -g
else ifeq ($(config),Release)
override CPPFLAGS += -DNDEBUG
override CFLAGS += -O2
override CXXFLAGS += -O2
else ifneq (,$(config))
$(warning Unknown configuration "$(config)")
endif
#
# Additionally, this makefile is customizable with the following
# settings:
#
#      ITTIA_DB_HOME  Path to ITTIA DB SDK

# Use "make RANLIB=''" for platforms without ranlib.
RANLIB ?= ranlib

CC := cc
CXX := c++

# ------------
# Configurable settings:
# 

# Path to ITTIA DB SDK
ITTIA_DB_HOME ?= /opt/ittiadb

# ------------

all: application file_storage memory_storage error_handling data_model security shared_access sql

application:
	$(MAKE) -C src/application -f GNUmakefile all

file_storage:
	$(MAKE) -C src/file_storage -f GNUmakefile all

memory_storage:
	$(MAKE) -C src/memory_storage -f GNUmakefile all

error_handling:
	$(MAKE) -C src/error_handling -f GNUmakefile all

data_model:
	$(MAKE) -C src/data_model -f GNUmakefile all

security:
	$(MAKE) -C src/security -f GNUmakefile all

shared_access:
	$(MAKE) -C src/shared_access -f GNUmakefile all

sql:
	$(MAKE) -C src/sql -f GNUmakefile all

clean:
	$(MAKE) -C src/application -f GNUmakefile clean
	$(MAKE) -C src/file_storage -f GNUmakefile clean
	$(MAKE) -C src/memory_storage -f GNUmakefile clean
	$(MAKE) -C src/error_handling -f GNUmakefile clean
	$(MAKE) -C src/data_model -f GNUmakefile clean
	$(MAKE) -C src/security -f GNUmakefile clean
	$(MAKE) -C src/shared_access -f GNUmakefile clean
	$(MAKE) -C src/sql -f GNUmakefile clean

.PHONY: all clean application file_storage memory_storage error_handling data_model security shared_access sql
